# Generated by Django 2.1.7 on 2019-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ras_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
                ('cpu_temperature', models.CharField(max_length=255)),
                ('cpu_useage', models.CharField(max_length=255)),
                ('harddrive_useage', models.CharField(max_length=255)),
            ],
        ),
    ]
