# Generated by Django 2.1.7 on 2019-03-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_data', '0002_auto_20190306_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ras_info',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
